# Generated by Django 3.2.7 on 2022-01-28 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='passmanager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Website', models.CharField(max_length=100, null=True)),
                ('Username', models.CharField(max_length=100, null=True)),
                ('password', fernet_fields.fields.EncryptedField(max_length=50)),
                ('frk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Passodata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
